import Image from "next/image";
import BackButton from "@/components/BackButton";
import SiteFooter from "@/components/SiteFooter";

export const metadata = {
  title: "Privacy | Read-Only Solana Analytics | TRAXR-SOLANA",
  description:
    "Privacy notice for the TRAXR-SOLANA read-only Solana analytics platform. No wallet connection, no transactions, no account creation.",
  alternates: {
    canonical: "/privacy",
  },
};

export default function PrivacyPage() {
  return (
    <main className="relative min-h-screen overflow-hidden px-6 py-10 sm:px-10 lg:px-16">
      <div className="pointer-events-none absolute inset-0 gridlines opacity-40" />

      <div className="relative mx-auto flex max-w-6xl flex-col gap-10 text-white">
        <BackButton />

        <section className="relative overflow-hidden rounded-3xl border border-white/10 bg-gradient-to-br from-[#0b1220]/90 via-[#0f1f36]/70 to-[#0b0f1d]/80 p-6 shadow-[0_0_80px_rgba(0,255,255,0.14)] sm:p-8">
          <div className="absolute inset-0 bg-[radial-gradient(circle_at_20%_20%,rgba(0,255,255,0.12),transparent_35%),radial-gradient(circle_at_80%_0%,rgba(0,180,255,0.12),transparent_28%)]" />

          <div className="relative mx-auto max-w-4xl">
            <div className="mb-10 flex flex-col items-start gap-4 sm:flex-row sm:items-center">
              <Image
                src="/images/TRAXR.png"
                alt="TRAXR-SOLANA"
                width={120}
                height={120}
                priority
                className="opacity-90"
              />
              <span className="text-xs tracking-wide text-slate-400 sm:text-sm">
                TRAXR-SOLANA | Privacy
              </span>
            </div>

            <h1 className="text-2xl font-semibold tracking-tight sm:text-3xl">
              Privacy
            </h1>
            <p className="mt-4 max-w-3xl text-sm tracking-wide text-slate-400">
              TRAXR-SOLANA is a public, read-only analytics interface for
              Solana liquidity pools. The product is designed to avoid account
              creation, wallet connection, and direct user submissions.
            </p>

            <section className="mt-10 rounded-2xl border border-cyan-400/20 bg-cyan-400/[0.08] p-5">
              <div className="text-xs uppercase tracking-[0.26em] text-cyan-200/80">
                Plain-English Summary
              </div>
              <p className="mt-3 text-sm leading-7 text-slate-200">
                TRAXR-SOLANA does not ask you to sign in, connect a wallet,
                submit private keys, or enter seed phrases. The interface is
                intended for read-only browsing of publicly sourced pool data.
              </p>
            </section>

            <section className="mt-10">
              <h2 className="text-lg font-medium sm:text-xl">
                Information We Intentionally Request
              </h2>
              <p className="mt-3 text-slate-300">
                None through the site interface. There are no login flows, no
                profile forms, no newsletter fields, and no wallet approval
                requests on TRAXR-SOLANA.
              </p>
            </section>

            <section className="mt-10">
              <h2 className="text-lg font-medium sm:text-xl">
                Public Analytics Data
              </h2>
              <p className="mt-3 text-slate-300">
                The platform displays indexed market and pool information
                derived from Solana liquidity data and internal scoring logic.
                These datasets describe pools and tokens, not visitor accounts.
              </p>
            </section>

            <section className="mt-10 rounded-md border border-white/10 bg-white/5 p-4">
              <h2 className="text-lg font-medium sm:text-xl">
                Operational Logging
              </h2>
              <p className="mt-3 text-slate-300">
                Like most hosted web services, standard network and server logs
                may be generated by the hosting stack or infrastructure
                providers for reliability, debugging, and abuse prevention.
                TRAXR-SOLANA is not designed around user profiling, account
                storage, or behavioral monetization.
              </p>
            </section>

            <section className="mt-10">
              <h2 className="text-lg font-medium sm:text-xl">Cookies</h2>
              <p className="mt-3 text-slate-300">
                TRAXR-SOLANA does not provide account or checkout features that
                require application cookies. Any browser-level storage or
                provider-managed technical cookies would be limited to normal
                site delivery and performance behavior.
              </p>
            </section>

            <section className="mt-10">
              <h2 className="text-lg font-medium sm:text-xl">Contact</h2>
              <p className="mt-3 text-slate-300">
                For privacy or security questions, contact
                <a
                  href="mailto:support@crosswalk.pro"
                  className="ml-1 text-cyan-200 hover:text-white"
                >
                  support@crosswalk.pro
                </a>
                .
              </p>
            </section>
          </div>
        </section>

        <SiteFooter />
      </div>
    </main>
  );
}
